### ISSUE TITLE
Change master branch to main

### ISSUE THREAD

**Issue by Otavio-Burato** [RodrigoDornelles/3bc-lang#105]
For years, some developers have regarded certain programming terminology most notably "master/slave" as racially problematic. For example, there was a push a few years ago to remove those terms from Python documentation, which led to much heated discussion.

Google’s Android and Chrome teams have likewise been determined to replace terms such as “blacklist” and “whitelist” within their respective codebases. "Blacklist" and "whitelist" reinforce the notion that black==bad and white==good. From now, the Google will use 'allow list' and 'deny list'.

The industry is making the shift of naming a project's default branch, "main", from the prior standard, "master". The change has already been happening so the sooner you get all your settings to change the less tricky it will be to make the adjustment later. So here are some steps in order to make the shift.

```` bash
git branch -m master main

git push -u origin main

git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/main

git push origin --delete master

**Comment by RodrigoDornelles** [comment]
I think these completely useless and irrelevant, who considers technical terminology of thing "racist" is inconsistent.
