### ISSUE TITLE
drop sort cpu mode

### ISSUE THREAD

**Issue by RodrigoDornelles** [RodrigoDornelles/3bc-lang#190]
> @marcusmmmz  said sometimes it feels like i'm making an x86 part 2 with certain unnecessary complexities 😢

I don't see reasons for it to be implemented, there is no real gain in maintaining it, but it takes up a lot of space unnecessarily. 

this issue is related to #120 #89 #44

**Comment by RodrigoDornelles** [comment]
#191

**Comment by marcusmmmz** [comment]
> > @marcusmmmz  said sometimes it feels like i'm making an x86 part 2 with certain unnecessary complexities
![image](https://user-images.githubusercontent.com/30752235/132780269-71473e0c-61d6-46d3-8217-426768be0c86.png)
