### ISSUE TITLE
Bad hashing with very simple solution

### ISSUE THREAD

**Issue by oluigipo** [RodrigoDornelles/3bc-lang#201]
https://github.com/RodrigoDornelles/3bc-lang/blob/7d985450590a1e63159033a22fe73753353a2421/src/3bc_macros.h#L105-106

### Problems
Uses up-to 10 bits of the 32-bit integer storing the hash; (Maximum value is 255 + 255 + 255 + 255 = 1020, which needs just 10 bits to be stored)
Too much collisions.

### Solution
I suggest doing `c1 | c2 << 8 | c3 << 16 | c4 << 24` instead. It will use the whole 32-bit space and will have **zero collisions** with 4 chars identifiers.

### Final Code
```c
#define PARSER_UNPACK(c)                (tolower(c[0])|tolower(c[1])<<8|tolower(c[2])<<16|tolower(c[3])<<24)
#define PARSER_PACK(c1,c2,c3,c4,v,r)    case(c1|c2<<8|c3<<16|c4<<24):*v=r;return(true)
```

**Comment by RodrigoDornelles** [comment]
This has been implemented, works correctly!

_an observation is that now there is no possibility of making mnemonics written in reverse_ 😆
