### ISSUE TITLE
There is no output filename at build rule

### ISSUE THREAD

**Issue by flavioipiranga** [RodrigoDornelles/3bc-lang#231]
There is no definition to the binary output file at:
https://github.com/RodrigoDornelles/3bc-lang/blob/2ccd51fb79f4f9f0bbc21b45105f2bb708d469ab/Makefile#L31

At [https://3bc-lang.org/guide/tutorial-pt-br](url) the recommendation it is to run using ./3bc.

**Comment by RodrigoDornelles** [comment]
done.
