### ISSUE TITLE
Random value in stri when using adresses

### ISSUE THREAD

**Issue by marcusmmmz** [RodrigoDornelles/3bc-lang#25]
```
mode 0 0x2
strc 0 'C'
stri 0x03 0
```
prints C27

```
mode 0 6
aloc 0x03 5
mode 0 0x2
strc 0 'C'
stri 0x03 0
```
prints C22

**Comment by RodrigoDornelles** [comment]
was unable to repeat this error on any OS, however twice it was reported by windows users, have are something to be investigated.

**Comment by RodrigoDornelles** [comment]
please compile and try the current code, there was an improvement in memory 9eeddc511dd3a673fa2eb4ef756fa5298859daf5

**Comment by RodrigoDornelles** [comment]
@marcusmmmz can you test with the latest build for windows?
<https://github.com/RodrigoDornelles/3bc-lang/releases>

**Comment by marcusmmmz** [comment]
Can't test on windows right now, but i probably will be able to later

**Comment by marcusmmmz** [comment]
tested it in windows in the new version
```
mode 0 6
aloc 0x03 5
mode 0 0x2
strc 0 'C'
stri 0x03 0
```
printed C5

```
mode 0 0x2
strc 0 'C'
stri 0x03 0
```
printed C0

it seems to work now.
