### ISSUE TITLE
Valor de variaveis errado

### ISSUE THREAD

**Issue by andreluispy** [RodrigoDornelles/3bc-lang#30]
Estava testando a 3BC mas detectei um erro na versão compilada hoje dia 31/12/2020

Ao execultar muitas vezes um script em 3bc as varias vezes a variavel é retornada de forma errada

Codigo:
```
mode nill 0x6
aloc 0X01 'A'
aloc 0X02 'B'
aloc 0X03 'C'

mode nill 0x02
strc 0X01 nill
strc 0X02 nill
strc 0X03 nill
```

Video de testes anexado:

https://user-images.githubusercontent.com/70450809/103422398-fc414d80-4b7f-11eb-8d9e-e68113dfa859.mp4

**Comment by RodrigoDornelles** [comment]
duplicate #25
