### ISSUE TITLE
O codigo só é rodado uma vez no console

### ISSUE THREAD

**Issue by andreluispy** [RodrigoDornelles/3bc-lang#32]
Fui rodar o codigo para inverter variaveis:

```
mode nill 0x06
aloc 0x01 'A'
aloc 0x02 'B'
aloc 0x03 'C'

mode nill 0x08
push 0x01 nill
pull 0x04 nill
push 0x03 nill
pull 0x01 nill
push 0x04 nill
pull 0x03 nill

mode nill 0x02
strc 0x01 nill
strc 0x02 nill
strc 0x03 nill
```

E só consigo rodar 1 vez por console, video de teste:

https://user-images.githubusercontent.com/70450809/103447253-549f4a80-4c67-11eb-9c1c-2f67b3049d19.mp4

**Comment by RodrigoDornelles** [comment]
I am studying posix rules, there may be some differences between I / Os between operating systems with different levels of portability.

I believe that due to the buffering mode of the standard output, it may fail on some windows systems, try `mode nill 1` (debug) if errors persist and report me please.

**Comment by andreluispy** [comment]
> Estou estudando regras posix, pode haver algumas diferenças entre I / Os entre sistemas operacionais com diferentes níveis de portabilidade.
> 
> Acredito que, devido ao modo de buffer da saída padrão, ele pode falhar em alguns sistemas Windows, tente `mode nill 1`(depure) se os erros persistirem e me informe por favor.

Os erros persistem

**Comment by andreluispy** [comment]
@RodrigoDornelles Eu devo ter escrito algo errado, agora deu certo com esse codigo:

```
MODE NILL 0x6
ALOC 0X01 'A' 
ALOC 0X02 'B' 
ALOC 0X03 'C' 

MODE NILL 0x02
STRC 0X01 NILL 
STRC 0X02 NILL 
STRC 0X03 NILL

MODE NILL 0x08
PUSH 0x01 NILL 
PULL 0x0A NILL 
PUSH 0x03 NILL 
PULL 0x01 NILL 
PUSH 0x0A NILL 
PULL 0x03 NILL 

MODE NILL 0x02
STRC 0X01 NILL 
STRC 0X02 NILL 
STRC 0X03 NILL
```
