### ISSUE TITLE
Nenhum código compila

### ISSUE THREAD

**Issue by GuriDev** [RodrigoDornelles/3bc-lang#33]
Quando tento compilar qualquer código, inclusive os exemplos ele me dá erro na linha 1 com código de erro 15, dizendo "INVALID REGISTER"

**Comment by RodrigoDornelles** [comment]
I need more information, such as operating system, and processor architecture.

if you are using windows try saving with utf8 encoding before running a file and tell me if it worked!

![image](https://user-images.githubusercontent.com/29123479/103458446-0cc00800-4ce7-11eb-88b3-adf65bd332f8.png)

**Comment by GuriDev** [comment]
> I need more information, such as operating system, and processor architecture.
> 
> if you are using windows try saving with utf8 encoding before running a file and tell me if it worked!
> 
> ![image](https://user-images.githubusercontent.com/29123479/103458446-0cc00800-4ce7-11eb-88b3-adf65bd332f8.png)
> 

Windows 10 Home (Single Language)
i5 x64
I always saved with utf8 encoding, so I tried saving with ANSI encoding and get the same problem agian

**Comment by GuriDev** [comment]
Tava executando errado o tempo todo hahahaha
