### ISSUE TITLE
add dark theme on docs page

### ISSUE THREAD

**Issue by luas10c** [RodrigoDornelles/3bc-lang#331]
* Add dark theme in docs page for acessibility

**Comment by fernandounger** [comment]
> * Add dark theme in docs page for acessibility

This functionality is already being implemented, soon you will be able to navigate between pages using the dark theme.

[3bc.webm](https://user-images.githubusercontent.com/87918106/184354990-5fc50415-ee34-4d6f-a141-86146667b939.webm)
