### ISSUE TITLE
remove all 'for' loops from source code

### ISSUE THREAD

**Issue by RodrigoDornelles** [RodrigoDornelles/3bc-lang#344]
by the ANSI standard the first field of `for` ends up not being used to instantiate variables, besides using while would be something simpler and more readable to maintain.

### before ###

```c
int i = 0;

for (; i < sizeof(any); i++) {
   /** code **/
}
```

### after ###

```c
int i = 0;

while(i < sizeof(any)) {
   /** code **/
   i += 1;
}
```

**Comment by Yugal41735** [comment]
Hello, @RodrigoDornelles is this issue still active?

**Comment by RodrigoDornelles** [comment]
> Hello, @RodrigoDornelles is this issue still active?

Yes.

**Comment by Yugal41735** [comment]
So, for this issue I basically have to just replace for with while, and where exactly I had to do this?

**Comment by Yugal41735** [comment]
So, like do I have to visit every single file, and if there's a for loop present then I have to replace it with while? @RodrigoDornelles

**Comment by RodrigoDornelles** [comment]
> So, like do I have to visit every single file, and if there's a for loop present then I have to replace it with while? 

browse the code or use a search tool, all sources are in the `src/` path, just apply a similar iteration to `for()` using `while()` keeping the initial behavior.

**Comment by Yugal41735** [comment]
@RodrigoDornelles  I had created the pr regarding the same, you could review it.

**Comment by RodrigoDornelles** [comment]
>  I had created the pr regarding the same, you could review it.

Tanks!

I've reviewed it, if u make some small changes I'll run the automatic tests to merge.
