### ISSUE TITLE
add git-hooks and create a commit standards 

### ISSUE THREAD

**Issue by RodrigoDornelles** [RodrigoDornelles/3bc-lang#357]
I'm very new to this, and also disorganized, if you can suggest a pattern and even implement it would help us!

**Comment by AllanSiqueira** [comment]
Can I help with this issue?
There is this convention for commit names, what do you think about it?
https://www.conventionalcommits.org/en/v1.0.0/

**Comment by RodrigoDornelles** [comment]
> Can I help with this issue? There is this convention for commit names, what do you think about it? https://www.conventionalcommits.org/en/v1.0.0/

@AllanSiqueira yes, that's great for me.

if you want to implement it I give you some suggestions to use **shellscript** or **ruby**.<br/>_(I know python is common for hooks, but it would be an extra dependency for the project in which you already use ruby)_

Remembering that it's October, so it will be accepted as a valid contribution to hacktoberfest! :smile:

**Comment by AllanSiqueira** [comment]
I will work on it!
Thank you!
