### ISSUE TITLE
The web is down

### ISSUE THREAD

**Issue by nguyengiabach1201** [RodrigoDornelles/3bc-lang#422]
## Describe the bug
3bc-lang.org is down (I'm in Vietnam and I don't know is it because my geography or not)

**Comment by RodrigoDornelles** [comment]
@nguyengiabach1201 **thanks for letting me know! the domain was expired, but I can pay on time.**

Unfortunately, it's chaos for me, and I also had to use the little money I had. I am currently homeless due to a catastrophe in Rio Grande do Sul, Brazil.
