### ISSUE TITLE
Wrong Gramatic

### ISSUE THREAD

**Issue by jevrton** [RodrigoDornelles/3bc-lang#76]
Have some gramatical errors on the text, one of them is on **Documentation** area, where have "*clice* here" hyperlink.
The other error is on **How to Compile** windows area, in the hyperlink, the same error.
![preview_2](https://user-images.githubusercontent.com/58525177/115128626-6823b680-9fb5-11eb-95d0-2a033e7f1db1.png)
![preview_1](https://user-images.githubusercontent.com/58525177/115128628-68bc4d00-9fb5-11eb-80ac-d481e7383db3.png)

**Comment by RodrigoDornelles** [comment]
Solved #77
